// data-extra.js — 500+ additional sites appended to DATA
// Sources: GitHub awesome lists, Reddit r/InternetIsBeautiful, X threads, Instagram reels
(function () {
    const EXTRA = [
        {
            id: "ai-music-audio", name: "AI Music & Audio", icon: "🎵", type: "free",
            desc: "Generate full songs, split tracks, clone voices, and create studio-quality audio with AI — all free.",
            sites: [
                { n: "Suno AI", u: "https://suno.com", d: "Generate radio-quality songs with lyrics from a text prompt. The most viral AI music tool ever made.", l: "Free: 50 credits/day", s: "Viral on Instagram & X" },
                { n: "Udio", u: "https://www.udio.com", d: "Create full songs in any genre with AI — chorus, verse, bridge. Full structure from one prompt.", l: "Free tier available", s: "Viral on Instagram reels" },
                { n: "ElevenLabs", u: "https://elevenlabs.io", d: "Ultra-realistic AI voice generation. Clone any voice, dub videos in 29 languages, generate audiobooks.", l: "Free: 10k chars/month", s: "Seen on @setupsai & X" },
                { n: "StemRoller", u: "https://www.stemroller.com", d: "Separate any song into vocals, drums, bass, and instruments free. Powered by Meta's Demucs AI.", l: "None", s: "Viral on Reddit & X" },
                { n: "Vocal Remover", u: "https://vocalremover.org", d: "Remove vocals from any song or isolate the instrumental track — free, instant, no signup.", l: "None", s: "Viral on Instagram & X" },
                { n: "Soundraw", u: "https://soundraw.io", d: "AI music for creators — generate royalty-free tracks by mood, genre, and length instantly.", l: "Free tier available", s: "Instagram reels" },
                { n: "Mubert", u: "https://mubert.com", d: "AI-generated royalty-free music streams. Unique background music for videos, streams, apps.", l: "Free tier limited", s: "Found via research" },
                { n: "Boomy", u: "https://boomy.com", d: "Create AI songs in seconds. Distribute them to Spotify, Apple Music, TikTok and earn royalties.", l: "Free tier available", s: "Found via research" },
                { n: "Freesound", u: "https://freesound.org", d: "600k+ free audio clips, sound effects, and loops with Creative Commons licenses.", l: "Free account for downloads", s: "GitHub awesome lists" },
                { n: "LMMS", u: "https://lmms.io", d: "Free open-source DAW — create beats, melodies, and full tracks in your browser.", l: "None", s: "GitHub trending" },
                { n: "Beatoven.ai", u: "https://www.beatoven.ai", d: "Royalty-free AI music for content — select mood and genre, download for any project.", l: "Free: 15 min/month", s: "Found via research" },
                { n: "Loudly", u: "https://www.loudly.com", d: "AI music generator — royalty-free tracks instantly generated for video, podcasts, social.", l: "Free tier with limits", s: "Found via research" },
                { n: "Pixabay Music", u: "https://pixabay.com/music", d: "100% free music for any use — no attribution needed. Curated tracks updated daily.", l: "None", s: "Found via research" },
                { n: "Mixkit", u: "https://mixkit.co", d: "Free premium stock music, SFX, and video clips for content creators. No attribution required.", l: "None", s: "Found via research" },
                { n: "Melobytes", u: "https://melobytes.com", d: "AI music tools — text to song, image to music, melody harmonizer all free.", l: "Some tools require account", s: "Found via research" }
            ]
        },
        {
            id: "design-creative", name: "Design & Creative Tools", icon: "🎨", type: "free",
            desc: "3D design, motion graphics, illustrations, color tools, and creative utilities — all free.",
            sites: [
                { n: "Spline", u: "https://spline.design", d: "Design interactive 3D objects in your browser. Export to web, React, or video. Used by top teams.", l: "Free tier available", s: "Viral on X & Instagram" },
                { n: "Rive", u: "https://rive.app", d: "Create interactive animations and micro-interactions for apps and web. Tiny runtime files.", l: "Free tier available", s: "GitHub trending" },
                { n: "LottieFiles", u: "https://lottiefiles.com", d: "Free library of lightweight animations. Download as JSON, GIF, MP4 or use in React, iOS, Android.", l: "Pro for team features", s: "Seen on @setupsai" },
                { n: "Haikei", u: "https://haikei.app", d: "Generate unique SVG blobs, waves, gradients, and background shapes for websites.", l: "None", s: "Reddit r/webdev & X" },
                { n: "Vectorizer.ai", u: "https://vectorizer.ai", d: "Convert any image into a crisp SVG vector with AI. Instant, clean results.", l: "Limited free conversions", s: "Viral Instagram design reels" },
                { n: "Krea.ai", u: "https://www.krea.ai", d: "Real-time AI image generation. Paint with AI and see results live as you sketch.", l: "Free tier daily limits", s: "Viral on X" },
                { n: "Pika.art", u: "https://pika.art", d: "AI video generator — turn text, images, or clips into cinematic short videos in seconds.", l: "Free tier with watermark", s: "Viral on Instagram & X" },
                { n: "Coolors", u: "https://coolors.co", d: "Fastest color palette generator on the internet. Press spacebar for a new palette. Save, export.", l: "Pro for team features", s: "GitHub awesome lists" },
                { n: "Dora.run", u: "https://www.dora.run", d: "Build animated 3D websites without code. AI-generated designs. Next-gen website builder.", l: "Free tier available", s: "Viral X product hunts" },
                { n: "Ray.so", u: "https://ray.so", d: "Create beautiful shareable screenshots of code with themes and syntax highlighting.", l: "None", s: "Seen on @setupsai" },
                { n: "Shots.so", u: "https://shots.so", d: "Create stunning mockup screenshots for apps, websites, and social media instantly.", l: "Free tier available", s: "Instagram design reels" },
                { n: "Storyset", u: "https://storyset.com", d: "Free customizable vector illustrations by Freepik. Change colors and animate for any project.", l: "Attribution on free tier", s: "GitHub awesome lists" },
                { n: "CSS Gradient", u: "https://cssgradient.io", d: "Visual CSS gradient builder. Create, preview, and copy CSS gradient code for any project.", l: "None", s: "Reddit r/webdev" },
                { n: "Namelix", u: "https://namelix.com", d: "AI business name generator. Keywords in, catchy brandable names out — with logo ideas.", l: "None", s: "Seen on @setupsai" },
                { n: "Luma AI", u: "https://lumalabs.ai", d: "Capture real objects in 3D with your phone. Embed interactive 3D on any website.", l: "Free tier available", s: "Viral on Instagram & X" },
                { n: "Framer", u: "https://www.framer.com", d: "Build pixel-perfect websites with animations and AI. No code needed. Deploy instantly.", l: "Free tier with Framer domain", s: "Found via research" },
                { n: "Adobe Express", u: "https://www.adobe.com/express", d: "Free design for social posts, logos, flyers, videos. 1000s of templates by Adobe.", l: "Premium assets need sub", s: "Found via research" },
                { n: "Wunderbucket", u: "https://wunderbucket.io", d: "Drop images onto 3D device mockups (iPhone, Mac, iPad) and export for portfolios.", l: "Free tier available", s: "Found via research" },
                { n: "Favicon.io", u: "https://favicon.io", d: "Generate favicon.ico from text, emoji, or image in seconds. All sizes included.", l: "None", s: "GitHub awesome lists" },
                { n: "FontJoy", u: "https://fontjoy.com", d: "Generate beautiful font pairings with AI. Getting heading+body pairs that actually work.", l: "None", s: "Reddit r/webdev & Instagram" }
            ]
        },
        {
            id: "dev-utilities", name: "Developer Utilities", icon: "💻", type: "free",
            desc: "Code tools, regex testers, API testing, converters, and dev utilities — all free in your browser.",
            sites: [
                { n: "Transform.tools", u: "https://transform.tools", d: "Convert between 30+ data formats — JSON to TypeScript, HTML to JSX, CSS to JS, and more.", l: "None", s: "GitHub trending" },
                { n: "Regex101", u: "https://regex101.com", d: "Test and debug regular expressions with real-time highlighting and plain English explanations.", l: "None", s: "GitHub awesome lists" },
                { n: "ExplainShell", u: "https://explainshell.com", d: "Paste any shell command and get a visual breakdown of every argument and flag.", l: "None", s: "Reddit r/linux & GitHub" },
                { n: "BundlePhobia", u: "https://bundlephobia.com", d: "Check the cost of any npm package. See bundle size, download time, and alternatives.", l: "None", s: "GitHub trending" },
                { n: "Hoppscotch", u: "https://hoppscotch.io", d: "Open-source API testing — REST, GraphQL, WebSocket. The free beautiful Postman alternative.", l: "None (30k+ stars)", s: "GitHub trending" },
                { n: "CyberChef", u: "https://gchq.github.io/CyberChef", d: "GCHQ's tool for encoding, decoding, encrypting, hashing, analyzing data. 300+ operations.", l: "None", s: "Viral X security threads" },
                { n: "Public APIs", u: "https://publicapis.dev", d: "Searchable index of 1,400+ free public APIs with categories, auth type, and CORS info.", l: "None", s: "GitHub (300k stars)" },
                { n: "DevDocs", u: "https://devdocs.io", d: "Unified documentation for 100+ APIs. Search MDN, Node, Python, and more offline.", l: "None", s: "GitHub awesome lists" },
                { n: "SQLiteOnline", u: "https://sqliteonline.com", d: "Run SQL queries directly in your browser. Import CSV/JSON, build schemas instantly.", l: "None", s: "GitHub awesome lists" },
                { n: "Webhook.site", u: "https://webhook.site", d: "Instant unique URL to inspect, test, and debug webhooks and HTTP requests in real time.", l: "Free with limits", s: "GitHub awesome lists" },
                { n: "CodeSandbox", u: "https://codesandbox.io", d: "Instant cloud dev environment. Start React, Vue, Next.js projects in your browser.", l: "Free public projects", s: "GitHub trending" },
                { n: "StackBlitz", u: "https://stackblitz.com", d: "Online IDE powered by WebContainers. Run Node.js, React, full-stack apps in the tab.", l: "Free tier available", s: "GitHub trending" },
                { n: "Netlify Drop", u: "https://app.netlify.com/drop", d: "Drag and drop any folder to get a live HTTPS URL instantly. No account needed.", l: "None for basic drops", s: "Viral X dev community" },
                { n: "Insomnia", u: "https://insomnia.rest", d: "Open-source API client for REST, GraphQL, gRPC. Git sync, env variables, clean UI.", l: "None", s: "GitHub trending" },
                { n: "WAVE Accessibility", u: "https://wave.webaim.org", d: "Free web accessibility evaluator. Check any URL for WCAG errors instantly.", l: "None", s: "GitHub awesome lists" },
                { n: "GTmetrix", u: "https://gtmetrix.com", d: "Website speed test with waterfall chart, Core Web Vitals, and specific fix recommendations.", l: "Limited reports free", s: "Found via research" },
                { n: "Gitignore.io", u: "https://www.toptal.com/developers/gitignore", d: "Generate perfect .gitignore files for any stack — OS, IDE, language combinations.", l: "None", s: "GitHub (widely used)" },
                { n: "JSON Crack", u: "https://jsoncrack.com", d: "Visualize JSON, YAML, CSV as interactive node graphs you can explore and edit.", l: "Free with size limits", s: "GitHub trending" },
                { n: "Vercel", u: "https://vercel.com", d: "Deploy any front-end for free in seconds. Automatic HTTPS, CI/CD, global CDN.", l: "Bandwidth limits on free", s: "Found via research" },
                { n: "Carbon", u: "https://carbon.now.sh", d: "Create beautiful, shareable images of your source code. Used by devs everywhere.", l: "None", s: "Found via research" }
            ]
        },
        {
            id: "finance-life", name: "Finance & Life Tools", icon: "💰", type: "free",
            desc: "Money tracking, virtual cards, document signing, price alerts, and life-improving utilities.",
            sites: [
                { n: "Privacy.com", u: "https://privacy.com", d: "Create virtual credit card numbers for online shopping. Stops unwanted charges forever.", l: "US only; limits on free", s: "Viral Reddit & X" },
                { n: "Bitwarden", u: "https://bitwarden.com", d: "Best free open-source password manager. Unlimited passwords, cross-device sync, security audit.", l: "Premium $10/yr for extras", s: "GitHub top project" },
                { n: "CamelCamelCamel", u: "https://camelcamelcamel.com", d: "Track Amazon price history. Set alerts when prices drop. Never overpay on Amazon again.", l: "None", s: "Viral Reddit r/deals & Instagram" },
                { n: "Honey", u: "https://www.joinhoney.com", d: "Browser extension that auto-applies coupon codes at checkout across 30k+ stores.", l: "None", s: "Found via research" },
                { n: "Wise", u: "https://wise.com", d: "International money transfers at the real exchange rate. Far cheaper than banks.", l: "Small transfer fee", s: "Found via research" },
                { n: "ChatPDF", u: "https://www.chatpdf.com", d: "Upload any PDF and chat with it using AI. Perfect for contracts, textbooks, research.", l: "Free: 2 PDFs/day", s: "Viral on Instagram & X" },
                { n: "Splitwise", u: "https://www.splitwise.com", d: "Track shared expenses and split bills with friends and roommates. Settle up easily.", l: "Pro for receipt scanning", s: "Found via research" },
                { n: "Coupert", u: "https://www.coupert.com", d: "Auto-applies best coupon codes at checkout from 50,000+ stores. Works where Honey doesn't.", l: "None", s: "Found via research" },
                { n: "GasBuddy", u: "https://www.gasbuddy.com", d: "Find the cheapest gas near you in real time. Compare stations, save on every fill-up.", l: "None", s: "Found via research" },
                { n: "Canva Resume", u: "https://www.canva.com/resumes/templates", d: "100s of free beautiful resume templates. Design and download a pro resume in minutes.", l: "Some templates need Pro", s: "Found via research" },
                { n: "LinkedIn", u: "https://www.linkedin.com", d: "Professional networking, job search, and industry news. Connect, apply, grow your career.", l: "Premium for recruiter tools", s: "Found via research" },
                { n: "NerdWallet", u: "https://www.nerdwallet.com", d: "Free financial tools — compare credit cards, loans, mortgages with unbiased expert reviews.", l: "None", s: "Found via research" },
                { n: "Sharesight", u: "https://www.sharesight.com", d: "Free investment portfolio tracker. Tracks stocks, ETFs, crypto with accurate return data.", l: "Free: 10 holdings", s: "Found via research" },
                { n: "Robinhood", u: "https://robinhood.com", d: "Commission-free stock, ETF, and crypto trading. No minimum balance required.", l: "Gold tier for extras", s: "Found via research" },
                { n: "Credit Karma", u: "https://creditkarma.com", d: "Free credit score monitoring, bill tracking, and personalized financial recommendations.", l: "None", s: "Found via research" },
                { n: "Currenzy", u: "https://currenzy.app", d: "Real-time currency converter with 170+ currencies. Clean, fast, no ads.", l: "None", s: "Reddit r/InternetIsBeautiful" },
                { n: "SignNow", u: "https://www.signnow.com", d: "Free electronic signature tool. Upload, sign, and send PDFs for legally binding sigs.", l: "Free tier with limits", s: "Found via research" },
                { n: "Moonpay", u: "https://www.moonpay.com", d: "Buy crypto instantly with card or bank. Supports 100+ cryptocurrencies, fast KYC.", l: "Transaction fees apply", s: "Found via research" },
                { n: "Firefly III", u: "https://www.firefly-iii.org", d: "Free open-source personal finance manager. Self-host your own money tracking dashboard.", l: "Self-hosting required", s: "GitHub trending" },
                { n: "Every Dollar", u: "https://www.everydollar.com", d: "Simple zero-based budget app. Give every dollar a job. Free version covers the basics.", l: "Plus plan for bank sync", s: "Found via research" }
            ]
        },
        {
            id: "hidden-gems", name: "Hidden Gems & Utilities", icon: "💎", type: "free",
            desc: "Unique, lesser-known tools that feel like cheats — viral on Reddit, Instagram reels, and X threads.",
            sites: [
                { n: "12ft.io", u: "https://12ft.io", d: "Prepend 12ft.io/ to any URL to bypass soft paywalls. Works on most news sites instantly.", l: "None", s: "Viral Reddit & Instagram" },
                { n: "ShareDrop", u: "https://www.sharedrop.io", d: "AirDrop for all devices — transfer files on same WiFi, no account, no cloud.", l: "None", s: "Viral on Instagram & X" },
                { n: "Wormhole", u: "https://wormhole.app", d: "End-to-end encrypted file sharing up to 10GB. Link expires automatically after 24h.", l: "Free: 10GB, 24hr", s: "Viral Reddit r/privacy" },
                { n: "10 Minute Mail", u: "https://10minutemail.com", d: "Instant disposable email that auto-expires after 10 minutes. Stop spam forever.", l: "None", s: "Viral on Instagram reels" },
                { n: "Fast.com", u: "https://fast.com", d: "Netflix's speed test. Clean, instant, no ads. Shows latency and upload speed too.", l: "None", s: "Viral on Instagram reels" },
                { n: "Downdetector", u: "https://downdetector.com", d: "Real-time status checks for any website. Know if Netflix, Spotify, etc. are down.", l: "None", s: "Viral on X & Reddit" },
                { n: "Outline.com", u: "https://outline.com", d: "Paste any paywalled article URL to read it clean, ad-free. Bypasses most news paywalls.", l: "None", s: "Viral on Reddit & X" },
                { n: "GuerillaMail", u: "https://www.guerrillamail.com", d: "Disposable email with real inbox. Set custom address and receive actual email.", l: "None", s: "Found via research" },
                { n: "WhatTheFont", u: "https://www.myfonts.com/pages/whatthefont", d: "Identify any font from an image or screenshot. Upload and get the exact font name.", l: "None", s: "Seen on @setupsai" },
                { n: "Similarsites", u: "https://www.similarsites.com", d: "Discover websites similar to any site. Find competitors, alternatives, related content.", l: "None", s: "Seen on @setupsai" },
                { n: "Unpaywall", u: "https://unpaywall.org", d: "Browser extension that finds free legal versions of academic papers at paywalls.", l: "None", s: "Viral Reddit r/scholar" },
                { n: "Favicon.io", u: "https://favicon.io", d: "Generate favicons from text, emoji, or image in seconds. Export all required sizes.", l: "None", s: "GitHub awesome lists" },
                { n: "Webhook.site", u: "https://webhook.site", d: "Instantly get a URL to inspect webhooks and HTTP requests in real time. Debug easily.", l: "Free with limits", s: "GitHub awesome lists" },
                { n: "Screenshot One", u: "https://screenshotone.com", d: "Take screenshots of any webpage via URL parameter. Add to URL, get screenshot back.", l: "Free tier available", s: "Found via research" },
                { n: "Send.cm", u: "https://send.cm", d: "Upload up to 5GB files, share direct download links. No account, links last 30 days.", l: "File size limits", s: "Found via research" },
                { n: "Flighty", u: "https://www.flightyapp.com", d: "Best flight tracker. Real-time alerts for delays and gate changes before airlines announce.", l: "Free tier available", s: "Found via research" },
                { n: "Playpivotal", u: "https://playpivotal.com", d: "Historical crossroads moments game — make the decision, then see what actually happened.", l: "None", s: "Reddit r/InternetIsBeautiful" },
                { n: "Livegrid", u: "https://livegrid.app", d: "Explore what the world is watching right now — live global TV from any country.", l: "None", s: "Reddit r/InternetIsBeautiful" },
                { n: "Radio.garden", u: "https://radio.garden", d: "Explore live radio from every country by spinning an interactive 3D globe.", l: "None", s: "Seen on @setupsai" },
                { n: "Sigilla", u: "https://sigilla.net", d: "Self-cleaning read-it-later app. Save links, and they auto-archive to prevent digital hoarding.", l: "None", s: "Reddit r/InternetIsBeautiful" }
            ]
        },
        {
            id: "ai-writing-research", name: "AI Writing & Research", icon: "✍️", type: "free",
            desc: "AI-powered writing assistants, research tools, summarizers, and content generators.",
            sites: [
                { n: "Claude.ai", u: "https://claude.ai", d: "Anthropic's Claude — 200k token context window. Best for long documents, nuanced writing, coding.", l: "Free tier available", s: "Viral on X AI community" },
                { n: "DeepSeek", u: "https://chat.deepseek.com", d: "Chinese AI that beats GPT-4 on benchmarks — completely free, no waitlist, blazing fast.", l: "None", s: "Viral on X & Reddit Jan 2025" },
                { n: "Mistral Le Chat", u: "https://chat.mistral.ai", d: "European AI model. Fast, free, no signup needed. Great for coding and structured tasks.", l: "None", s: "Found via research" },
                { n: "Poe.com", u: "https://poe.com", d: "Access Claude, GPT-4, Gemini, and 100+ AI bots in one place. Switch models mid-conversation.", l: "Daily message limits", s: "Seen on @setupsai" },
                { n: "HuggingChat", u: "https://huggingface.co/chat", d: "Open-source AI chatbots — Llama, Mistral, and more. Free, no account needed.", l: "None", s: "GitHub (Hugging Face)" },
                { n: "Perplexity", u: "https://perplexity.ai", d: "AI search engine with real-time answers and cited sources. Best for research and fact-checking.", l: "Pro for advanced models", s: "Viral on X" },
                { n: "You.com", u: "https://you.com", d: "AI-powered search engine with citations and an assistant that browses the web for you.", l: "Free tier available", s: "Found via research" },
                { n: "Quillbot", u: "https://quillbot.com", d: "AI paraphrasing, grammar checking, and summarizer. Rewrite any text in 7 different modes.", l: "Premium for full features", s: "Viral Instagram tools reels" },
                { n: "Hemingway App", u: "https://hemingwayapp.com", d: "Make your writing bold and clear. Grades readability, catches passive voice and complexity.", l: "None for web version", s: "Found via research" },
                { n: "Notion AI", u: "https://www.notion.so/product/ai", d: "AI built into Notion workspace. Summarize, translate, generate content inline.", l: "Within Notion free tier", s: "Found via research" },
                { n: "Gamma", u: "https://gamma.app", d: "AI-powered presentation and document generator. Professional slides from text prompts.", l: "Free: Gamma branding", s: "Seen on @setupsai" },
                { n: "Napkin.ai", u: "https://napkin.ai", d: "Convert text into visuals, diagrams, and infographics instantly with AI.", l: "Freemium model", s: "Seen on @setupsai" },
                { n: "Wordvice AI", u: "https://wordvice.ai", d: "AI proofreader that corrects grammar, style, vocabulary, and structure. For academic writing.", l: "Free credits daily", s: "Found via research" },
                { n: "Jenni AI", u: "https://jenni.ai", d: "AI writing assistant for essays, research papers, and academic work. Autocomplete and citations.", l: "Free tier available", s: "Viral on Instagram student reels" },
                { n: "Copy.ai", u: "https://www.copy.ai", d: "AI copywriting tool for marketing copy, emails, social posts, and product descriptions.", l: "Free tier: 2k words/month", s: "Found via research" },
                { n: "Writesonic", u: "https://writesonic.com", d: "AI writer for blogs, ads, and landing pages. 80+ templates and a Chatsonic AI assistant.", l: "Free tier limited", s: "Found via research" },
                { n: "Kagi", u: "https://kagi.com", d: "Premium search engine with zero ads, zero tracking, and AI summary tools.", l: "100 searches/month free", s: "Viral X privacy community" },
                { n: "Consensus", u: "https://consensus.app", d: "AI search engine that searches 200M+ scientific papers and summarizes findings.", l: "Free tier available", s: "Found via research" },
                { n: "Explainpaper", u: "https://www.explainpaper.com", d: "Upload any academic paper, highlight confusing parts, get plain English explanations with AI.", l: "Free tier with limits", s: "Viral on Reddit r/MachineLearning" },
                { n: "NotebookLM", u: "https://notebooklm.google.com", d: "Google's AI notebook — audio overviews, mind maps, study guides from your own documents.", l: "None", s: "Seen on @setupsai & X" }
            ]
        },
        {
            id: "productivity-focus", name: "Productivity & Focus", icon: "⚡", type: "free",
            desc: "Timers, note-taking, task management, automation, and focus tools to get more done.",
            sites: [
                { n: "Notion", u: "https://notion.so", d: "All-in-one workspace for notes, wikis, tasks, and databases. The internet's favorite productivity app.", l: "Free: limited blocks for teams", s: "Found via research" },
                { n: "Obsidian", u: "https://obsidian.md", d: "Local-first note-taking with backlinks and a knowledge graph. Your second brain, fully private.", l: "Free for personal use", s: "GitHub trending" },
                { n: "Excalidraw", u: "https://excalidraw.com", d: "Virtual whiteboard for hand-drawn style diagrams. Collaborate in real time, no account.", l: "Plus for extras", s: "GitHub (50k+ stars)" },
                { n: "Todoist", u: "https://todoist.com", d: "Best-in-class task manager with natural language input, priorities, and recurring tasks.", l: "Free: 5 projects", s: "Found via research" },
                { n: "TickTick", u: "https://ticktick.com", d: "Task and habit tracker with Pomodoro timer and focus stats. Clean UI, generous free tier.", l: "Premium for calendar sync", s: "Found via research" },
                { n: "Habitica", u: "https://habitica.com", d: "Turn your habits into an RPG game. Earn XP and level up your character by completing tasks.", l: "None", s: "Viral Reddit r/productivity" },
                { n: "Forest App", u: "https://forestapp.cc", d: "Stay focused by growing virtual trees. Leave the app and your tree dies. Gamified focus timer.", l: "Free tier available", s: "Viral on Instagram productivity reels" },
                { n: "Pomofocus", u: "https://pomofocus.io", d: "Clean Pomodoro timer in the browser. 25 min work, 5 min break. No account needed.", l: "None", s: "Viral on Reddit & X" },
                { n: "Focusmate", u: "https://www.focusmate.com", d: "Virtual co-working accountability sessions. Book sessions, work alongside others via video.", l: "Free: 3 sessions/week", s: "Viral on Reddit r/productivity" },
                { n: "Zapier", u: "https://zapier.com", d: "Automate workflows between 6,000+ apps. No-code automation for repetitive tasks.", l: "Free: 100 tasks/month", s: "Found via research" },
                { n: "Make.com", u: "https://www.make.com", d: "Visual workflow automation — more powerful than Zapier, better free tier and visual builder.", l: "Free: 1000 ops/month", s: "Found via research" },
                { n: "n8n", u: "https://n8n.io", d: "Open-source workflow automation. Self-host or use cloud. Code when you need to.", l: "Free self-hosted", s: "GitHub trending" },
                { n: "Trello", u: "https://trello.com", d: "Visual Kanban boards for project management. Drag and drop tasks between lists.", l: "Free: 10 boards", s: "Found via research" },
                { n: "Linear", u: "https://linear.app", d: "Fastest issue tracker for software teams. Keyboard-first, beautiful design, built-in roadmaps.", l: "Free for small teams", s: "Viral X dev community" },
                { n: "Raycast", u: "https://www.raycast.com", d: "macOS productivity launcher with AI, clipboard history, snippets, and 1000s of extensions.", l: "Free; Pro for AI", s: "Viral X & GitHub" },
                { n: "Cron Calendar", u: "https://cron.com", d: "Notion's calendar app. Beautiful, keyboard-first scheduling for professionals.", l: "Free tier available", s: "Found via research" },
                { n: "Calendly", u: "https://calendly.com", d: "Share your availability, let others book meetings without the email back-and-forth.", l: "Free: 1 event type", s: "Found via research" },
                { n: "Loom", u: "https://www.loom.com", d: "Record quick video messages with screen and camera. Replace long emails with async video.", l: "Free: 25 videos", s: "Found via research" },
                { n: "Otter.ai", u: "https://otter.ai", d: "AI meeting transcription with speaker ID. Transcribe Zoom, Meet, Teams meetings automatically.", l: "Free: 300 mins/month", s: "Found via research" },
                { n: "Reflect Notes", u: "https://reflect.app", d: "Network note-taking app powered by AI. Notes connect and resurface when relevant.", l: "Paid ($10/mo)", s: "Viral X productivity community" }
            ]
        },
        {
            id: "cybersecurity-privacy", name: "Cybersecurity & Privacy", icon: "🔐", type: "free",
            desc: "Security tools, privacy browsers, password managers, breach checkers, and anonymity tools.",
            sites: [
                { n: "Have I Been Pwned", u: "https://haveibeenpwned.com", d: "Check if your email or phone has been in any known data breach. The essential security check.", l: "None", s: "Viral on Instagram security reels" },
                { n: "2FA Directory", u: "https://2fa.directory", d: "Find out which websites support two-factor authentication and how to enable it.", l: "None", s: "GitHub awesome lists" },
                { n: "VirusTotal", u: "https://www.virustotal.com", d: "Scan any file, URL, or domain with 70+ antivirus engines instantly. Free threat intelligence.", l: "None", s: "Found via research" },
                { n: "DNSleaktest", u: "https://www.dnsleaktest.com", d: "Test your VPN for DNS leaks. Ensure your real IP and DNS aren't exposed.", l: "None", s: "Found via research" },
                { n: "BrowserLeaks", u: "https://browserleaks.com", d: "Test what information your browser leaks — IP, WebRTC, Canvas fingerprint, and more.", l: "None", s: "Viral Reddit r/privacy" },
                { n: "Shodan", u: "https://www.shodan.io", d: "Search engine for internet-connected devices. Find exposed servers, cams, and IoT devices.", l: "Free tier limited", s: "Viral X security community" },
                { n: "CyberChef", u: "https://gchq.github.io/CyberChef", d: "GCHQ's Swiss army knife for data — encode, decode, encrypt, hash. 300+ operations.", l: "None", s: "Viral X security threads" },
                { n: "Malwarebytes", u: "https://www.malwarebytes.com", d: "Free malware scanner and removal tool. Detects threats antivirus misses.", l: "Premium for real-time protection", s: "Found via research" },
                { n: "Privacy Badger", u: "https://privacybadger.org", d: "EFF's tracker blocker that learns as you browse. Automatically blocks invisible trackers.", l: "None", s: "Found via research" },
                { n: "SimpleLogin", u: "https://simplelogin.io", d: "Create unlimited email aliases to protect your real email. Forward to your inbox, reply anonymously.", l: "Free: 10 aliases", s: "Viral Reddit r/privacy" },
                { n: "Bitwarden", u: "https://bitwarden.com", d: "Best free open-source password manager. Unlimited passwords, cross-device sync, breach monitoring.", l: "Premium $10/yr", s: "GitHub top open-source" },
                { n: "KeePassXC", u: "https://keepassxc.org", d: "Free offline password manager. Your passwords stay local — never touch a cloud server.", l: "None", s: "GitHub trending" },
                { n: "Authy", u: "https://authy.com", d: "Best free 2FA authenticator app. Encrypted cloud backup so you never lose your codes.", l: "None", s: "Found via research" },
                { n: "AdGuard DNS", u: "https://adguard-dns.io", d: "Free DNS-level ad and tracker blocker. One setting change blocks ads on all devices.", l: "Free tier available", s: "Found via research" },
                { n: "Quad9 DNS", u: "https://www.quad9.net", d: "Free private DNS with built-in malware blocking. Faster, safer, and more private than Google DNS.", l: "None", s: "Found via research" },
                { n: "Cryptomator", u: "https://cryptomator.org", d: "Free transparent encryption for cloud files. Works with Dropbox, Google Drive, OneDrive.", l: "None for desktop", s: "GitHub (10k+ stars)" },
                { n: "ProtonMail", u: "https://proton.me", d: "End-to-end encrypted email. Swiss privacy laws. Zero-knowledge — even Proton can't read your mail.", l: "Free: 1GB storage", s: "Found via research" },
                { n: "Signal", u: "https://signal.org", d: "The most secure messaging app. Open-source, end-to-end encrypted, zero data collection.", l: "None", s: "Found via research" },
                { n: "Securedrop", u: "https://securedrop.org", d: "Whistleblower submission platform used by major news orgs. Completely anonymous document leak.", l: "For journalists/sources only", s: "Found via research" },
                { n: "Tails OS", u: "https://tails.boum.org", d: "Privacy-focused OS. Boots from USB, routes all traffic through Tor, leaves zero trace.", l: "None", s: "Found via research" }
            ]
        },
        {
            id: "learning-education", name: "Learning & Education", icon: "📚", type: "edu",
            desc: "Free world-class education — full university courses, coding bootcamps, language learning, and more.",
            sites: [
                { n: "Khan Academy", u: "https://khanacademy.org", d: "World-class K-12 education in math, science, computing, and history. 100% free forever.", l: "None", s: "Found via research" },
                { n: "Coursera Audit", u: "https://www.coursera.org", d: "Audit 7,000+ courses from Stanford, Yale, Google for free. Certificate costs money.", l: "Certificate requires payment", s: "Found via research" },
                { n: "MIT OpenCourseWare", u: "https://ocw.mit.edu", d: "Free course materials from MIT — lecture notes, exams, and videos from real courses.", l: "None", s: "Found via research" },
                { n: "freeCodeCamp", u: "https://www.freecodecamp.org", d: "Learn web dev, Python, data science, and more. Free courses + verified certifications.", l: "None", s: "GitHub (390k stars)" },
                { n: "The Odin Project", u: "https://www.theodinproject.com", d: "Full-stack web dev curriculum. Project-based learning, HTML to Rails. 100% free.", l: "None", s: "GitHub awesome lists" },
                { n: "CS50 Harvard", u: "https://cs50.harvard.edu", d: "Harvard's intro to computer science. The most popular CS course ever — free online.", l: "Certificate costs money", s: "Found via research" },
                { n: "Exercism", u: "https://exercism.org", d: "Master 67+ programming languages with exercises and free mentorship from real developers.", l: "None", s: "GitHub trending" },
                { n: "Duolingo", u: "https://www.duolingo.com", d: "Learn 40+ languages for free. Gamified lessons that keep you coming back daily.", l: "Plus for ad-free", s: "Found via research" },
                { n: "Brilliant", u: "https://brilliant.org", d: "Interactive math, science, and CS courses. Learn by solving challenging puzzles and problems.", l: "Free: limited content", s: "Found via research" },
                { n: "edX", u: "https://www.edx.org", d: "Audit courses from MIT, Harvard, Berkeley for free. Verified certificates available.", l: "Certificate requires payment", s: "Found via research" },
                { n: "Codecademy", u: "https://www.codecademy.com", d: "Interactive coding lessons in Python, JavaScript, SQL, and more. Learn by doing.", l: "Pro for full access", s: "Found via research" },
                { n: "LeetCode", u: "https://leetcode.com", d: "Practice coding interview problems. 3000+ challenges used by Google, Amazon, and Meta.", l: "Premium for premium problems", s: "Found via research" },
                { n: "HackerRank", u: "https://www.hackerrank.com", d: "Coding challenges and certifications. Improve Python, SQL, algorithms, and data structures.", l: "Free tier available", s: "Found via research" },
                { n: "Wolfram Alpha", u: "https://www.wolframalpha.com", d: "Computational knowledge engine. Answers math, science, data, and factual questions.", l: "Pro for step-by-step", s: "Found via research" },
                { n: "Anki", u: "https://apps.ankiweb.net", d: "The best spaced repetition flashcard system. Study anything, never forget it.", l: "Free (app $25 on iOS)", s: "Found via research" },
                { n: "Quizlet", u: "https://quizlet.com", d: "Create and study flashcards, matching games, and practice tests. 500M+ study sets.", l: "Plus for full features", s: "Found via research" },
                { n: "Crash Course", u: "https://thecrashcourse.com", d: "YouTube's best free educational series — history, science, lit, psychology, and coding.", l: "None", s: "Found via research" },
                { n: "3Blue1Brown", u: "https://www.3blue1brown.com", d: "Grant Sanderson's visual math videos. Makes calculus, linear algebra, and neural nets beautiful.", l: "None", s: "Viral YouTube/Reddit" },
                { n: "Stanford Online", u: "https://online.stanford.edu", d: "Free Stanford courses on CS, data science, AI, business, and medicine.", l: "Some courses charge fees", s: "Found via research" },
                { n: "fast.ai", u: "https://www.fast.ai", d: "Free practical deep learning course. Top-down approach used by world-class ML practitioners.", l: "None", s: "GitHub trending" }
            ]
        },
        {
            id: "movies-piracy", name: "Movies & TV (Piracy)", icon: "🎥", type: "piracy",
            desc: "Stream movies and TV shows free. Use a VPN and adblocker for best safety.",
            sites: [
                { n: "Cineby", u: "https://cineby.app", d: "Best free streamer — Netflix-like UI, auto-next episodes, subtitles, zero intrusive ads.", l: "Adblocker recommended", s: "Top Pick" },
                { n: "SFlix", u: "https://sflix.to", d: "Huge movie and TV library. Clean UI, multiple server options, HD streams.", l: "Adblocker + VPN recommended", s: "Found via research" },
                { n: "MyFlixer", u: "https://myflixer.to", d: "Netflix alternative with HD streams and 50k+ titles across genres.", l: "VPN recommended", s: "Found via research" },
                { n: "AZMovies", u: "https://azmovies.ag", d: "Clean movie streaming site. Multiple servers, HD quality, fast loading.", l: "Adblocker recommended", s: "Found via research" },
                { n: "Fmovies", u: "https://www.fmoviesz.to", d: "One of the oldest and most-used free streaming sites. Huge library, multiple mirrors.", l: "VPN + Adblocker recommended", s: "Found via research" },
                { n: "123Movies", u: "https://www.123moviesfree.net", d: "Classic streaming site with extensive TV and movie library. Multiple working mirrors.", l: "VPN + Adblocker recommended", s: "Found via research" },
                { n: "Soap2Day", u: "https://www.soap2day.ac", d: "Popular free streaming site for movies and shows. Clean layout, many server options.", l: "VPN recommended", s: "Found via research" },
                { n: "Tubi", u: "https://tubitv.com", d: "100% legal free streaming. 50k+ titles, ad-supported. No VPN needed.", l: "Has ads", s: "Legal pick" },
                { n: "Pluto TV", u: "https://pluto.tv", d: "Legal free live TV and on-demand. 300+ channels, thousands of movies and shows.", l: "Ad-supported", s: "Legal pick" },
                { n: "Plex (Free)", u: "https://plex.tv", d: "Legal free content — movies, TV, live TV with news, sports, and entertainment.", l: "Ad-supported", s: "Legal pick" },
                { n: "Crackle", u: "https://www.crackle.com", d: "Sony's free streaming service. Movies and originals with no subscription needed.", l: "Ad-supported", s: "Legal pick" },
                { n: "Popcornflix", u: "https://www.popcornflix.com", d: "Legal free streaming with hundreds of movies across all genres.", l: "Ad-supported", s: "Legal pick" },
                { n: "Kanopy", u: "https://www.kanopy.com", d: "Free streaming through your public library card. Art films, documentaries, classics.", l: "Requires library card", s: "Legal pick" },
                { n: "Vumoo", u: "https://vumoo.to", d: "Clean free streaming site with extensive movie and TV library.", l: "VPN recommended", s: "Found via research" },
                { n: "LookMovie2", u: "https://lookmovie2.to", d: "High-quality movie streams. Clean interface, works without account.", l: "VPN + Adblocker", s: "Found via research" },
                { n: "OnionPlay", u: "https://onionplay.co", d: "Extensive free streaming library. Fast servers, good video quality.", l: "VPN recommended", s: "Found via research" },
                { n: "Letmewatchthis", u: "https://www.letmewatchthis.ac", d: "Classic streaming aggregator. Link database for movies and shows.", l: "VPN recommended", s: "Found via research" },
                { n: "Bflix", u: "https://bflix.gg", d: "High-quality 4K streaming for movies and shows. Fast servers, clean ads.", l: "VPN recommended", s: "Found via research" },
                { n: "IOMovies", u: "https://iomovies.stream", d: "Large free streaming library with fast servers and good stream quality.", l: "VPN recommended", s: "Found via research" },
                { n: "Primewire", u: "https://www.primewire.tf", d: "One of the oldest movie streaming sites. Community ratings and multiple mirrors.", l: "VPN recommended", s: "Found via research" }
            ]
        },
        {
            id: "sports-streaming", name: "Sports Streaming", icon: "⚽", type: "sports",
            desc: "Watch NFL, NBA, UFC, soccer, F1, and more live — free sports streams. Use a VPN and adblocker.",
            sites: [
                { n: "Buffstream", u: "https://ms.buffstream.io", d: "Reliable streams for NFL, NBA, MLB, NHL, MMA, boxing. Minimal ads, good quality.", l: "VPN + Adblocker", s: "Top Pick" },
                { n: "Streameast", u: "https://www.streameast.live", d: "NFL, NBA, NHL, MMA, and more. Clean interface, multiple stream options.", l: "VPN + Adblocker", s: "Found via research" },
                { n: "VIPRow", u: "https://vipleague.im", d: "Free sports streams across all major leagues. Multi-sport coverage in one place.", l: "VPN recommended", s: "Found via research" },
                { n: "SportsBay", u: "https://sportsbay.org", d: "Live sports streaming for soccer, tennis, basketball, MMA, and more.", l: "VPN recommended", s: "Found via research" },
                { n: "CrackStreams", u: "https://crackstreams.io", d: "Premier free sports streaming. NFL, NBA, MLB, NHL, UFC — all covered.", l: "VPN + Adblocker", s: "Found via research" },
                { n: "Feed2all", u: "https://www.feed2all.co", d: "Soccer-focused streaming with global league coverage. Clean interface.", l: "VPN recommended", s: "Found via research" },
                { n: "LiveTV", u: "https://livetv.sx", d: "Comprehensive sports streams. Soccer, basketball, tennis, hockey, and more.", l: "VPN recommended", s: "Found via research" },
                { n: "FirstRow Sports", u: "https://firstrow.eu", d: "Classic free sports streams. NFL, soccer, basketball, tennis.", l: "VPN + Adblocker", s: "Found via research" },
                { n: "Hesgoal", u: "https://www.hesgoal.live", d: "Free football/soccer streaming. Focused on Premier League, Champions League, and more.", l: "VPN recommended", s: "Found via research" },
                { n: "Ronaldo7", u: "https://www.ronaldo7.net", d: "Free soccer streaming. Specializes in Champions League, World Cup, and top leagues.", l: "VPN recommended", s: "Found via research" },
                { n: "CBS Sports (Free)", u: "https://www.cbssports.com", d: "Legal free sports content — NFL, NBA, College sports. Some live games free with ads.", l: "Some content requires CBS account", s: "Legal pick" },
                { n: "YouTube Sports", u: "https://youtube.com/sports", d: "Free NFL and NBA games on YouTube. Some matchups streamed live legally.", l: "Some games paywalled", s: "Legal pick" },
                { n: "ESPN (Free Content)", u: "https://espn.com", d: "News, highlights, scores, and some free games. ESPN+ for live premium content.", l: "ESPN+ for most live games", s: "Legal pick" },
                { n: "NBA League Pass (Free)", u: "https://www.nba.com/watch/free-preview", d: "NBA's official app has free preview content, highlights, and some out-of-market games.", l: "Full pass is paid", s: "Legal pick" },
                { n: "NFL+", u: "https://www.nfl.com/plus", d: "NFL's free tier includes live local/primetime games on mobile and team radio streams.", l: "Premium for full archive", s: "Legal pick" },
                { n: "MFCrack", u: "https://mfcr.gg", d: "Mixed martial arts and combat sports streaming — UFC, Bellator, boxing.", l: "VPN recommended", s: "Found via research" },
                { n: "Bilasport", u: "https://bilasport.net", d: "Sports streaming focused on NBA and Middle East sports coverage.", l: "VPN recommended", s: "Found via research" },
                { n: "Methstreams", u: "https://methstreams.com", d: "Free sports streaming for NFL, NBA, NHL. Simple interface, reliable links.", l: "VPN + Adblocker", s: "Found via research" },
                { n: "SportStream", u: "https://www.sportstream.io", d: "Global sports streaming hub. Soccer, basketball, tennis, F1, and esports.", l: "VPN recommended", s: "Found via research" },
                { n: "Futemax", u: "https://futemax.app", d: "Latin America's top free soccer streaming. Champions League, Libertadores, World Cup.", l: "VPN recommended", s: "Found via research" }
            ]
        }
    ];

    // Append to DATA array
    if (typeof DATA !== 'undefined') {
        EXTRA.forEach(function (cat) { DATA.push(cat); });
    }
})();
