if (!window.DATA) window.DATA = [];

window.DATA.push(
    {
        id: "game-emulators", name: "🎮 Game Emulators", icon: "🎮", type: "free",
        desc: "Play classic console and arcade games directly in your browser or download top emulators.",
        sites: [
            { n: "RetroGames.cc", u: "https://www.retrogames.cc/", d: "Play thousands of classic retro games from NES, SNES, Genesis, and Arcade directly in your browser.", l: "Adblocker recommended", s: "Top Pick" },
            { n: "MyEmulator.online", u: "https://myemulator.online/", d: "Play Nintendo, Sega, GBA, and Arcade games online for free with save states.", l: "None", s: "Popular" },
            { n: "EmulatorGames.net", u: "https://www.emulatorgames.net/", d: "Download ROMs and Emulators for GBA, SNES, N64, Nintendo DS, and PlayStation.", l: "Adblocker recommended", s: "Found via research" },
            { n: "Vimm's Lair", u: "https://vimm.net/", d: "The legendary, ad-free vault for classic console ROMs and Emulators. A staple of the retro community.", l: "None", s: "Community Favorite" },
            { n: "RetroArch", u: "https://www.retroarch.com/", d: "The ultimate frontend for emulators, game engines, and media players. Available on almost every platform.", l: "Open Source", s: "Must Have" },
            { n: "Dolphin Emulator", u: "https://dolphin-emu.org/", d: "Play GameCube and Wii games in full HD (1080p) with excellent compatibility.", l: "Open Source", s: "Top Emulator" },
            { n: "PCSX2", u: "https://pcsx2.net/", d: "The definitive PlayStation 2 emulator for Windows, Mac, and Linux.", l: "Open Source", s: "Top Emulator" },
            { n: "RPCS3", u: "https://rpcs3.net/", d: "Open-source PlayStation 3 emulator and debugger written in C++.", l: "Open Source", s: "Advanced" },
            { n: "Yuzu", u: "https://yuzu-emu.org/", d: "Experimental open-source emulator for the Nintendo Switch. (Note: Project discontinued, forks exist)", l: "Requires powerful PC", s: "Found via research" },
            { n: "Ryujinx", u: "https://ryujinx.org/", d: "Alternative open-source Nintendo Switch emulator with excellent accuracy and performance.", l: "None", s: "Popular Alternative" },
            { n: "Citra", u: "https://citra-emu.org/", d: "The premier Nintendo 3DS emulator. (Note: Project discontinued, forks exist)", l: "None", s: "Classic Emulator" },
            { n: "PPSSPP", u: "https://www.ppsspp.org/", d: "The best PSP emulator. Play PSP games in HD on PC, Android, and iOS.", l: "Open Source", s: "Mobile friendly" },
            { n: "DuckStation", u: "https://github.com/stenzek/duckstation", d: "Highly accurate PlayStation 1 emulator focusing on playability, speed, and long-term maintainability.", l: "Open Source", s: "GitHub Favorite" },
            { n: "mGBA", u: "https://mgba.io/", d: "Fast, accurate Game Boy Advance emulator.", l: "Open Source", s: "Top Pick" },
            { n: "Snes9x", u: "https://github.com/snes9xgit/snes9x", d: "Portable, freeware Super Nintendo Entertainment System (SNES) emulator.", l: "Open Source", s: "Reliable" },
            { n: "DeSmuME", u: "http://desmume.org/", d: "The most seasoned open-source Nintendo DS emulator.", l: "Open Source", s: "Found via research" },
            { n: "MAME", u: "https://www.mamedev.org/", d: "Multiple Arcade Machine Emulator. Preserve decades of software history.", l: "Open Source", s: "Arcade Standard" },
            { n: "PlayClassic.games", u: "https://playclassic.games/", d: "Browser-based emulation of DOS, Windows 3.x, and early console games.", l: "None", s: "Found via research" },
            { n: "ClassicReload", u: "https://classicreload.com/", d: "Preserving 6,000+ old DOS games and abandoned OS/Apps for browser play.", l: "Adblocker recommended", s: "Found via research" },
            { n: "Internet Archive: Software Library", u: "https://archive.org/details/softwarelibrary_msdos_games", d: "Massive collection of MS-DOS games playable directly in your browser via DOSBox.", l: "Free", s: "Archive" }
        ]
    },
    {
        id: "app-stores-apk", name: "📱 App Stores & APKs", icon: "📱", type: "free",
        desc: "Alternative app stores and sites to download Android APK files safely.",
        sites: [
            { n: "F-Droid", u: "https://f-droid.org/", d: "Installable catalogue of Free and Open Source Software (FOSS) applications for the Android platform.", l: "FOSS only", s: "Privacy Focused" },
            { n: "APKMirror", u: "https://www.apkmirror.com/", d: "Download safe, original APK files completely free from malware. Run by Android Police.", l: "Ads present", s: "Highly Trusted" },
            { n: "APKPure", u: "https://apkpure.com/", d: "Download free Android games and apps directly as APK or XAPK files.", l: "Adblocker recommended", s: "Popular" },
            { n: "Aurora Store", u: "https://auroraoss.com/", d: "Open-source Google Play Store client. Download apps anonymously without a Google account.", l: "FOSS", s: "Privacy Focused" },
            { n: "Aptoide", u: "https://en.aptoide.com/", d: "Alternative decentralized Android app store where users can create their own repositories.", l: "Caution with third-party repos", s: "Alternative Store" },
            { n: "Uptodown", u: "https://en.uptodown.com/android", d: "Open app store with millions of apps in APK format, no Google Play required.", l: "None", s: "Popular" },
            { n: "QooApp", u: "https://apps.qoo-app.com/en", d: "Must-have app store for downloading Asian/Japanese mobile games not available globally.", l: "None", s: "Niche Favorite" },
            { n: "APKCombo", u: "https://apkcombo.com/", d: "Fast APK downloader with older versions available and region-locked apps.", l: "Ads present", s: "Found via research" },
            { n: "TapTap", u: "https://www.taptap.io/", d: "Gaming community and app store focused on high-quality mobile games globally.", l: "None", s: "Gaming Focus" },
            { n: "XDA Labs", u: "https://www.xda-developers.com/", d: "Home for Android developers and modders. Find custom ROMs and unique apps.", l: "None", s: "Developer Community" },
            { n: "Mobilism", u: "https://forum.mobilism.org/", d: "Huge forum-based repository for modified and premium Android apps.", l: "Piracy risk if misused", s: "Advanced Users" },
            { n: "Softpedia Android", u: "https://mobile.softpedia.com/android/", d: "Curated collection of Android apps manually reviewed by the Softpedia team.", l: "None", s: "Reliable" },
            { n: "AppBrain", u: "https://www.appbrain.com/", d: "Discover the best Android apps and track app market statistics.", l: "None", s: "Found via research" },
            { n: "APK4Fun", u: "https://www.apk4fun.com/", d: "Download top trending Android apps and games safely.", l: "Adblocker recommended", s: "Found via research" },
            { n: "Droid-ify", u: "https://github.com/Droid-ify/client", d: "A lightweight material F-Droid client with an upgraded UI.", l: "FOSS", s: "UI Upgrade" }
        ]
    },
    {
        id: "ai-image-gen", name: "🤖 AI Image Gen", icon: "🎨", type: "ai",
        desc: "Generate stunning images, art, and assets using cutting-edge AI models.",
        sites: [
            { n: "Midjourney", u: "https://www.midjourney.com/", d: "Industry-leading AI image generator known for artistic quality and photorealism. Operates via Discord.", l: "Paid subscription", s: "Top Tier" },
            { n: "Stable Diffusion WebUI (AUTOMATIC1111)", u: "https://github.com/AUTOMATIC1111/stable-diffusion-webui", d: "Run Stable Diffusion locally on your PC. Complete control, uncensored, 100% free.", l: "Requires strong GPU", s: "Power Users" },
            { n: "Leonardo.ai", u: "https://leonardo.ai/", d: "Create production-quality visual assets for your projects with unprecedented quality and speed.", l: "Free daily tokens", s: "Great UI" },
            { n: "Civitai", u: "https://civitai.com/", d: "The premier hub for sharing and discovering custom Stable Diffusion models, LoRAs, and generations.", l: "NSFW content present", s: "Community Hub" },
            { n: "Tensor.art", u: "https://tensor.art/", d: "Host and run custom Stable Diffusion models online for free without needing a high-end GPU.", l: "Free daily generations", s: "Accessible" },
            { n: "SeaArt.ai", u: "https://seaart.ai/", d: "Powerful AI art generator similar to Leonardo with huge community model support.", l: "Free daily tokens", s: "Found via research" },
            { n: "DALL-E 3 (via Bing/Copilot)", u: "https://copilot.microsoft.com/images/create", d: "Free access to OpenAI's DALL-E 3 via Microsoft. Excellent prompt adherence.", l: "Free (Requires MS account)", s: "Best for text" },
            { n: "RunwayML", u: "https://runwayml.com/", d: "Advanced AI creative suite offering image, video, and audio generation tools.", l: "Freemium", s: "Video Gen Leader" },
            { n: "Ideogram", u: "https://ideogram.ai/", d: "Exceptional AI image generator that specializes in putting perfect text and typography into images.", l: "Free tier available", s: "Best Typography" },
            { n: "Krea.ai", u: "https://www.krea.ai/", d: "Real-time AI Canvas for instant image generation alongside real-time sketching.", l: "Freemium", s: "Real-time generation" },
            { n: "Fal.ai", u: "https://fal.ai/", d: "Lightning fast generative AI APIs. Try models like Flux.1 and SDXL incredibly fast.", l: "Pay per compute", s: "Developer focused" },
            { n: "Freepik Pikaso", u: "https://www.freepik.com/pikaso", d: "Real-time sketching to image AI and AI upscaling tools.", l: "Freemium", s: "Design Integration" },
            { n: "Playground AI", u: "https://playgroundai.com/", d: "Free-to-use online AI image creator. Create 500 images per day for free.", l: "Free tier", s: "High daily limit" },
            { n: "NightCafe", u: "https://creator.nightcafe.studio/", d: "AI art generator offering multiple algorithms including Stable Diffusion, DALL-E, and VQGAN+CLIP.", l: "Free daily credits", s: "Community focused" },
            { n: "Mage.space", u: "https://www.mage.space/", d: "Fast, free, and uncensored Stable Diffusion generation online.", l: "Freemium", s: "Uncensored" },
            { n: "Lexica", u: "https://lexica.art/", d: "Search engine for Stable Diffusion prompts and images, plus a competent built-in generator.", l: "Free limited generations", s: "Prompt inspiration" },
            { n: "PromeAI", u: "https://www.promeai.com/", d: "AI design assistant for architects, interior designers, and product designers.", l: "Freemium", s: "Professional focus" },
            { n: "Recraft", u: "https://www.recraft.ai/", d: "Infinite AI canvas for creating vector art, icons, 3D images and illustrations.", l: "Freemium", s: "Vector focused" },
            { n: "RenderNet", u: "https://rendernet.ai/", d: "Advanced control for AI image generation featuring ControlNet and character consistency.", l: "Freemium", s: "Character Consistency" },
            { n: "Dzine (formerly Stylar)", u: "https://www.dzine.ai/", d: "AI image editor providing layer logic and masking for precise image control.", l: "Freemium", s: "Layer-based" }
        ]
    },
    {
        id: "video-editing", name: "🎬 Video Editing & Creation", icon: "🎥", type: "free",
        desc: "Free video editors, VFX tools, and AI video generators.",
        sites: [
            { n: "CapCut", u: "https://www.capcut.com/", d: "The best free video editor for short-form content. Packed with transitions, effects, and AI tools.", l: "Watermark on pro features", s: "TikTok Standard" },
            { n: "DaVinci Resolve", u: "https://www.blackmagicdesign.com/products/davinciresolve", d: "Hollywood-grade video editing, color correction, and VFX. The free version is 95% of the paid studio version.", l: "Professional learning curve", s: "Industry Standard" },
            { n: "Kdenlive", u: "https://kdenlive.org/", d: "Open-source video editor perfect for Linux and Windows. Extremely reliable timeline editor.", l: "FOSS", s: "Open Source" },
            { n: "LosslessCut", u: "https://github.com/mifi/lossless-cut", d: "Extremely fast and lossless video/audio trimming tool. Cuts without re-encoding.", l: "FOSS", s: "Perfect for clipping" },
            { n: "OBS Studio", u: "https://obsproject.com/", d: "Free and open source software for video recording and live streaming.", l: "FOSS", s: "Must Have" },
            { n: "Sora (via OpenAI)", u: "https://openai.com/sora", d: "State-of-the-art text-to-video AI model generating ultra-realistic 60-second scenes.", l: "Limited availability", s: "AI Breakthrough" },
            { n: "Haiper API", u: "https://haiper.ai/", d: "Incredible free text-to-video AI generator with excellent motion and physics.", l: "Free generations", s: "AI Tool" },
            { n: "Kling AI", u: "https://klingai.com/", d: "Powerful AI video generator competing with Sora, capable of 2-minute generations.", l: "Daily free credits", s: "Top AI Video" },
            { n: "HandBrake", u: "https://handbrake.fr/", d: "The ultimate open-source video transcoder. Compress huge video files easily.", l: "FOSS", s: "Essential Tool" },
            { n: "Luma Dream Machine", u: "https://lumalabs.ai/dream-machine", d: "High-quality fast text-to-video AI model available for free public use.", l: "30 free gens/month", s: "AI Video" },
            { n: "Veed.io", u: "https://www.veed.io/", d: "Online video editor specializing in fast auto-subtitles and social media formatting.", l: "Watermarked", s: "Browser Editor" },
            { n: "Clipchamp", u: "https://clipchamp.com/", d: "Microsoft's free online video editor. Simple timeline and good stock library.", l: "MS Account required", s: "Beginner Friendly" },
            { n: "Shutter Encoder", u: "https://www.shutterencoder.com/", d: "Professional video and audio converter based on FFmpeg. Much more powerful than Handbrake.", l: "FOSS", s: "Pro Tool" },
            { n: "Pika Labs", u: "https://pika.art/", d: "Turn ideas into videos with this AI video generator. Good at stylistic animations.", l: "Daily credits", s: "AI Video" },
            { n: "Vidnoz AI", u: "https://www.vidnoz.com/", d: "AI video generation focused on human avatars and text-to-speech for presentations.", l: "Freemium", s: "Avatar Video" },
            { n: "Natron", u: "https://NatronGitHub.github.io/", d: "Open-source compositor for VFX and motion graphics. Alternative to After Effects.", l: "FOSS", s: "VFX Tool" },
            { n: "Shotcut", u: "https://shotcut.org/", d: "Free, open source, cross-platform video editor with broad format support.", l: "FOSS", s: "Solid Alternative" },
            { n: "Blender", u: "https://www.blender.org/", d: "Not just for 3D—it has a highly capable built-in non-linear video sequence editor.", l: "FOSS", s: "All-in-one" },
            { n: " Runway Gen-3 Alpha", u: "https://runwayml.com/", d: "High fidelity, fast, controllable video generation model.", l: "Paid", s: "VFX Grade" },
            { n: "HeyGen", u: "https://www.heygen.com/", d: "AI video creator making professional studio-quality spokesperson videos.", l: "Freemium", s: "Marketing AI" }
        ]
    },
    {
        id: "web3-crypto", name: "🌐 Web3 & Crypto", icon: "🪙", type: "tech",
        desc: "Tools, trackers, and platforms for cryptocurrency, DeFi, and blockchain.",
        sites: [
            { n: "CoinGecko", u: "https://www.coingecko.com/", d: "The best independent cryptocurrency data aggregator and price tracker.", l: "Free", s: "Top Tracker" },
            { n: "DexScreener", u: "https://dexscreener.com/", d: "Live charts and trading history for every token on decentralized exchanges.", l: "None", s: "DEX Essential" },
            { n: "DefiLlama", u: "https://defillama.com/", d: "The largest TVL aggregator for DeFi (Decentralized Finance). Find the best yields.", l: "Free", s: "DeFi Analytics" },
            { n: "Etherscan", u: "https://etherscan.io/", d: "The Ethereum blockchain explorer. Check transactions, wallets, and smart contracts.", l: "None", s: "Essential Explorer" },
            { n: "TradingView", u: "https://www.tradingview.com/", d: "The industry standard for financial charting, technical analysis, and social networking.", l: "Freemium", s: "Charting Standard" },
            { n: "CoinGlass", u: "https://www.coinglass.com/", d: "Crypto derivatives data, liquidations, funding rates, and open interest.", l: "None", s: "Derivatives Data" },
            { n: "Crypto Panic", u: "https://cryptopanic.com/", d: "News aggregator platform indicating impact on price and market for traders.", l: "None", s: "News Aggregator" },
            { n: "Airdrops.io", u: "https://airdrops.io/", d: "Aggregator of the latest, hottest, and legitimate crypto airdrops.", l: "Do your own research", s: "Airdrop Hunter" },
            { n: "DappRadar", u: "https://dappradar.com/", d: "Discover, track, and trade everything DeFi, NFT and Gaming.", l: "None", s: "Dapp Tracking" },
            { n: "Token Terminal", u: "https://tokenterminal.com/", d: "Financial metrics on crypto protocols. Evaluates blockchains like traditional businesses.", l: "Freemium", s: "Fundamental Analysis" },
            { n: "Zapper.fi", u: "https://zapper.fi/", d: "Dashboard for monitoring your DeFi portfolio, NFTs, and bridging assets.", l: "Wallet Login", s: "Portfolio Tracker" },
            { n: "Pump.fun", u: "https://pump.fun/", d: "Degenerate memecoin launchpad on Solana. High risk crypto casino.", l: "Extremely high risk", s: "Meme Central" },
            { n: "Arkham Intelligence", u: "https://www.arkhamintelligence.com/", d: "Deanonymizing the blockchain. See who owns wallets and track whale movements.", l: "Free", s: "On-chain sleuth" },
            { n: "Crypto Bubbles", u: "https://cryptobubbles.net/", d: "Interactive visual tool for cryptocurrency market dynamics.", l: "None", s: "Visual Data" },
            { n: "BubbleMaps", u: "https://bubblemaps.io/", d: "Audit token distribution and visualize wallet connections to spot insider trading.", l: "Freemium", s: "Security Tool" }
        ]
    },
    {
        id: "data-research", name: "📊 Data & Research", icon: "📈", type: "edu",
        desc: "Databases, research papers, demographics, and data visualization tools.",
        sites: [
            { n: "Our World in Data", u: "https://ourworldindata.org/", d: "Research and data to make progress against the world’s largest problems.", l: "Open Access", s: "Global Stats" },
            { n: "Statista", u: "https://www.statista.com/", d: "Global No.1 Business Data Platform. Insights into 170 industries and 150+ countries.", l: "Freemium", s: "Market Data" },
            { n: "Google Scholar", u: "https://scholar.google.com/", d: "Search across many disciplines and sources for academic articles, theses, books, and abstracts.", l: "None", s: "Academic Searching" },
            { n: "Sci-Hub", u: "https://sci-hub.se/", d: "The pirate bay of science. Bypasses publisher paywalls to provide free access to millions of research papers.", l: "Grey area", s: "Open Science" },
            { n: "Kaggle", u: "https://www.kaggle.com/", d: "Inside platform for data science teams. Find datasets, code, and machine learning models.", l: "Free tier", s: "Data Science Hub" },
            { n: "Archive.today", u: "https://archive.ph/", d: "Take a 'snapshot' of a webpage. The ultimate tool for bypassing news paywalls and preserving deleted pages.", l: "None", s: "Paywall Bypass" },
            { n: "Pew Research Center", u: "https://www.pewresearch.org/", d: "Nonpartisan fact tank informing the public about issues, attitudes and trends.", l: "Free", s: "Social Data" },
            { n: "Gapminder", u: "https://www.gapminder.org/", d: "Fights devastating ignorance with a fact-based worldview. Amazing interactive bubble charts.", l: "Free", s: "Data Visuals" },
            { n: "arXiv", u: "https://arxiv.org/", d: "Open-access archive for 2 million scholarly articles in physics, math, computer science, and more.", l: "Open Access", s: "Pre-prints" },
            { n: "Flourish", u: "https://flourish.studio/", d: "Beautiful and easy data visualization and storytelling for creating animated bar chart races and more.", l: "Freemium", s: "Interactive Visuals" },
            { n: "FRED (Federal Reserve Data)", u: "https://fred.stlouisfed.org/", d: "Download, graph, and track 800,000+ US and international time series from 114 sources.", l: "Free", s: "Eco Data" },
            { n: "PubMed", u: "https://pubmed.ncbi.nlm.nih.gov/", d: "More than 36 million citations for biomedical literature from MEDLINE, life science journals.", l: "Free", s: "Medical DB" },
            { n: "Data.gov", u: "https://www.data.gov/", d: "The home of the U.S. Government’s open data. Over 250,000 datasets.", l: "Free", s: "Gov Data" },
            { n: "Wolfram Alpha", u: "https://www.wolframalpha.com/", d: "Compute expert-level answers using Wolfram’s breakthrough algorithms and knowledgebase.", l: "Freemium", s: "Computational Engine" },
            { n: "Connected Papers", u: "https://www.connectedpapers.com/", d: "Explore academic papers in a visual graph to find related, prior, and derivative works.", l: "Freemium", s: "Literature Review" }
        ]
    },
    {
        id: "music-streaming", name: "🎵 Music Discovery", icon: "🎧", type: "free",
        desc: "Discover new music, convert playlists, stream for free, and download audio.",
        sites: [
            { n: "Suno AI", u: "https://suno.com/", d: "Create full, radio-quality songs from a simple text prompt. Best-in-class music generation.", l: "Daily free credits", s: "AI Music Leader" },
            { n: "Udio", u: "https://www.udio.com/", d: "Top competitor to Suno, offering incredible audio fidelity and manual tagging for song structures.", l: "Daily free credits", s: "AI Music Alternative" },
            { n: "Radio Garden", u: "https://radio.garden/", d: "Explore the globe by rotating a 3D earth and tuning into thousands of live radio stations worldwide.", l: "None", s: "Global Radio" },
            { n: "Every Noise at Once", u: "https://everynoise.com/", d: "Algorithmically-generated scatter-plot of the musical genre-space. Discover insanely niche genres.", l: "None", s: "Spotify Deep Data" },
            { n: "Bandcamp", u: "https://bandcamp.com/", d: "Discover amazing new music and directly support independent artists. Best platform for indie music.", l: "Purchase tracks", s: "Indie Ecosystem" },
            { n: "SpotDL", u: "https://spotdl.org/", d: "Spotify downloader. Download your playlists and songs from Spotify along with album art and metadata.", l: "Open Source script", s: "MP3 Downloader" },
            { n: "SoundCloud", u: "https://soundcloud.com/", d: "The world’s largest open audio platform. Home to underground rap, EDM mixes, and indie artists.", l: "Ads on free", s: "Underground Scene" },
            { n: "1001 Tracklists", u: "https://www.1001tracklists.com/", d: "Comprehensive DJ set tracklist database. Find out what song that DJ just dropped at the festival.", l: "None", s: "EDM Essential" },
            { n: "Tunebat", u: "https://tunebat.com/", d: "Find the Key & BPM (tempo) for millions of songs. Essential tool for DJs and mashup artists.", l: "None", s: "DJ Tool" },
            { n: "Gnoosic", u: "https://www.gnoosic.com/", d: "A self-adapting system that learns about music you like to recommend new bands you've never heard.", l: "None", s: "Discovery AI" },
            { n: "Rate Your Music", u: "https://rateyourmusic.com/", d: "Huge community-built database of albums, EPs, and singles. The IMDb for music nerds.", l: "None", s: "Music Ratings" },
            { n: "Chosic", u: "https://www.chosic.com/", d: "Playlist generator, mood-based discovery, and free background music for videos.", l: "None", s: "Playlist Tool" },
            { n: "Soundiiz", u: "https://soundiiz.com/", d: "Transfer your playlists between Spotify, Apple Music, YouTube Music, and Tidal easily.", l: "Freemium", s: "Playlist Converter" },
            { n: "FMA (Free Music Archive)", u: "https://freemusicarchive.org/", d: "Original music by independent artists, curated by WFMU. Free for legal, royalty-free download.", l: "CC Licensed", s: "Royalty Free" },
            { n: "WhoSampled", u: "https://www.whosampled.com/", d: "Explore the DNA of music. Find out who sampled whom, who covered whom, and who remixed whom.", l: "None", s: "Music History" },
            { n: "Gitaroo", u: "https://gitaroo.com/", d: "Learn to play guitar for free with interactive tabs and lessons.", l: "None", s: "Music Learning" },
            { n: "Audius", u: "https://audius.co/", d: "A decentralized, crypto-backed alternative to SoundCloud. Uncensored artist uploads.", l: "Web3", s: "Decentralized Music" },
            { n: "My 90s TV", u: "https://www.my90stv.com/", d: "Simulate watching TV in the 90s. Surfs through actual, curated YouTube videos of vintage broadcasts and MTV.", l: "None", s: "Nostalgia" },
            { n: "Lofigirl", u: "https://lofigirl.com/", d: "The legendary 24/7 lofi hip hop radio stream for studying and relaxing, directly in browser.", l: "None", s: "Study Beats" },
            { n: "Spotify Chart", u: "https://charts.spotify.com/", d: "Official Spotify charts for top 50 global, viral, and local country data.", l: "None", s: "Industry Data" }
        ]
    },
    {
        id: "photography-image", name: "📸 Photography & Image Tools", icon: "📷", type: "tech",
        desc: "Remove backgrounds, upscale images, compress photos, and edit pictures for free.",
        sites: [
            { n: "Remove.bg", u: "https://www.remove.bg/", d: "Instantly remove the background from any photo automatically using AI.", l: "Free low-res", s: "Essential Tool" },
            { n: "Photopea", u: "https://www.photopea.com/", d: "Advanced free online photo editor supporting PSD, XCF, Sketch, XD and CDR formats. Essentially a free Photoshop clone.", l: "Ad supported", s: "Photoshop Alt" },
            { n: "TinyPNG", u: "https://tinypng.com/", d: "Smart WebP, PNG, and JPEG compression. Shrink image files significantly without losing visual quality.", l: "20 images/day", s: "Web Dev Tool" },
            { n: "Upscayl", u: "https://upscayl.org/", d: "Free and open source AI image upscaler. Can run entirely locally on your hard drive.", l: "FOSS", s: "Desktop Tool" },
            { n: "Clipdrop", u: "https://clipdrop.co/", d: "AI suite by Stability AI: remove backgrounds, cleanup objects, relight photos, and upscale.", l: "Freemium", s: "AI Toolkit" },
            { n: "Pixlr", u: "https://pixlr.com/", d: "Free photo editor and design maker right in your browser.", l: "Freemium", s: "Browser Editor" },
            { n: "Figma", u: "https://www.figma.com/", d: "The collaborative interface design tool. Excellent for vector graphics and UI mocking.", l: "Free tier exists", s: "Industry Standard" },
            { n: "Canva", u: "https://www.canva.com/", d: "Free design tool for presentations, video, social media. Incredibly intuitive for quick graphic design.", l: "Freemium", s: "Massive Popularity" },
            { n: "Squoosh", u: "https://squoosh.app/", d: "Google's web app that compresses and compares images with different codecs right in your browser.", l: "None", s: "Compression" },
            { n: "Let's Enhance", u: "https://letsenhance.io/", d: "AI image upscaler and enhancer. Good for fixing blurry or low-res photos.", l: "10 free credits", s: "Found via research" },
            { n: "WatermarkRemover.io", u: "https://www.watermarkremover.io/", d: "AI tool that automatically removes watermarks from images accurately.", l: "Free for personal use", s: "Found via research" },
            { n: "Pexels", u: "https://www.pexels.com/", d: "Hundreds of thousands of free stock photos and royalty-free images.", l: "CC0 License", s: "Stock Photos" },
            { n: "Unsplash", u: "https://unsplash.com/", d: "Beautiful, free images and photos that you can download and use for any project.", l: "Unsplash License", s: "Stock Photos" },
            { n: "Cleanup.pictures", u: "https://cleanup.pictures/", d: "Remove any object, defect, people, or text from your pictures in seconds.", l: "Free local processing", s: "Retouching" },
            { n: "Vector Magic", u: "https://vectormagic.com/", d: "Convert JPG/PNG to fully scalable vector art (SVG/EPS).", l: "Freemium", s: "Vectorization" }
        ]
    },
    {
        id: "maps-travel", name: "🗺️ Maps & Travel Tools", icon: "📍", type: "edu",
        desc: "Interactive maps, flight trackers, secret hotel deals, and geography tools.",
        sites: [
            { n: "Flightradar24", u: "https://www.flightradar24.com/", d: "Live global flight tracking. Click on any plane in the sky to see its origin, destination, and altitude.", l: "Freemium", s: "Live Tracker" },
            { n: "Google Earth Pro", u: "https://www.google.com/earth/versions/#earth-pro", d: "The advanced desktop version of Google Earth. Includes historical imagery to see how places looked decades ago.", l: "Free download", s: "Exploration" },
            { n: "Skiplagged", u: "https://skiplagged.com/", d: "Find cheap flights by booking tickets where your destination is a layover. Airlines hate this site.", l: "Controversial hack", s: "Travel Hack" },
            { n: "SeatGuru", u: "https://www.seatguru.com/", d: "See exactly which airline seats have extra legroom, limited recline, or a missing window before you book.", l: "None", s: "Travel Hack" },
            { n: "Atlas Obscura", u: "https://www.atlasobscura.com/", d: "The definitive guide to the world's hidden wonders and unusual, obscure travel destinations.", l: "None", s: "Exploration" },
            { n: "Windy", u: "https://www.windy.com/", d: "Beautiful, interactive global weather map showing live wind, rain, and temperature currents.", l: "None", s: "Weather Map" },
            { n: "Rome2Rio", u: "https://www.rome2rio.com/", d: "Discover how to get anywhere by plane, train, bus, ferry and automobile.", l: "None", s: "Travel Routing" },
            { n: "GeoGuessr", u: "https://www.geoguessr.com/", d: "Dropped in a random Google Street View location. Figure out where you are in the world.", l: "Freemium", s: "Geography Game" },
            { n: "Ventusky", u: "https://www.ventusky.com/", d: "Live 3D weather map showing meteorological data beautifully.", l: "None", s: "Weather Visualization" },
            { n: "Radio.Garden", u: "https://radio.garden/", d: "Explore live radio across the globe by spinning a 3D Earth.", l: "None", s: "Global Radio" },
            { n: "MarineTraffic", u: "https://www.marinetraffic.com/", d: "Live, global ship tracking intelligence. Track cargo ships, yachts, and tankers.", l: "Freemium", s: "Ship Tracker" },
            { n: "EarthCam", u: "https://www.earthcam.com/", d: "Network of live streaming webcams from famous locations, beaches, and cities worldwide.", l: "None", s: "Live Cams" },
            { n: "Oyster", u: "https://www.oyster.com/", d: "Brutally honest, un-doctored photos of hotels. Know what it really looks like before booking.", l: "None", s: "Hotel Reviews" },
            { n: "Nomad List", u: "https://nomadlist.com/", d: "Crowdsourced database of the best places in the world to live, work, and travel as a digital nomad.", l: "Freemium", s: "Remote Work" },
            { n: "Wikivoyage", u: "https://en.wikivoyage.org/", d: "The free, worldwide travel guide that anyone can edit.", l: "None", s: "Open Guide" }
        ]
    },
    {
        id: "food-recipe", name: "🍕 Food & Recipe Sites", icon: "🍳", type: "edu",
        desc: "Find recipes by ingredient, meal prep guides, and cooking tools.",
        sites: [
            { n: "Supercook", u: "https://www.supercook.com/", d: "Input the random ingredients you have left in your fridge, and it tells you exactly what recipes you can make.", l: "None", s: "Zero Waste" },
            { n: "Budget Bytes", u: "https://www.budgetbytes.com/", d: "Delicious, easy recipes designed for small budgets. Includes exact cost breakdowns.", l: "None", s: "Frugal Cooking" },
            { n: "Serious Eats", u: "https://www.seriouseats.com/", d: "Definitive recipes utilizing culinary science. Known for extremely thorough testing and Food Lab guides.", l: "None", s: "Culinary Science" },
            { n: "MyFridgeFood", u: "https://myfridgefood.com/", d: "Another excellent 'what's in my fridge' recipe generator with a simple checklist UI.", l: "None", s: "Found via research" },
            { n: "JustTheRecipe", u: "https://www.justtherecipe.com/", d: "Paste a recipe URL and it cuts out all the life stories, ads, and fluff. Just shows the ingredients and instructions.", l: "None", s: "Reader App" },
            { n: "Eat This Much", u: "https://www.eatthismuch.com/", d: "Automatic meal planner. Put in your diet goals and calories, and it builds a full grocery list and menu.", l: "Freemium", s: "Meal Prep" },
            { n: "Recipe Filter (Extension)", u: "https://chrome.google.com/webstore/detail/recipe-filter/hlgmmbgedempkjpnkjkombgndbbkndhm", d: "Chrome extension that automatically pulls recipe cards to the top of long food blogs.", l: "None", s: "Browser Extension" },
            { n: "BBC Good Food", u: "https://www.bbcgoodfood.com/", d: "Reliable, heavily tested recipes for everyday cooking.", l: "None", s: "British Staples" },
            { n: "AllRecipes", u: "https://www.allrecipes.com/", d: "The ultimate crowdsourced recipe site. Read the reviews to see how users modified the dish.", l: "None", s: "Massive Community" },
            { n: "Tasting History", u: "https://www.youtube.com/c/TastingHistory", d: "Max Miller recreates historical recipes (from Ancient Rome to the Titanic) and discusses the history.", l: "YouTube Channel", s: "Edu-tainment" },
            { n: "Binging with Babish", u: "https://www.bingingwithbabish.com/", d: "Recreating famous foods from movies and TV shows.", l: "None", s: "Pop Culture Food" },
            { n: "Chef John (Food Wishes)", u: "https://foodwishes.blogspot.com/", d: "Incredibly approachable, high-quality cooking tutorials spanning 15+ years.", l: "None", s: "YouTube Legend" },
            { n: "CopyKat Recipes", u: "https://copykat.com/", d: "Recreate your favorite restaurant meals (Olive Garden, Panera, etc.) exactly at home.", l: "None", s: "Restaurant Clones" },
            { n: "Wok of Life", u: "https://thewoksoflife.com/", d: "The definitive guide to authentic Chinese home cooking.", l: "None", s: "Niche Authority" },
            { n: "Half Baked Harvest", u: "https://www.halfbakedharvest.com/", d: "Stunningly photographed, comforting, and decadent recipes.", l: "None", s: "Food Photography" }
        ]
    },
    {
        id: "health-fitness", name: "💪 Health & Fitness Apps", icon: "🏋️", type: "free",
        desc: "Workout generators, macro trackers, and anatomical guides.",
        sites: [
            { n: "MuscleWiki", u: "https://musclewiki.com/", d: "Click on the exact muscle you want to work out on a 3D model, and it shows you gifs of exercises targeting it.", l: "None", s: "Visual App" },
            { n: "Darebee", u: "https://darebee.com/", d: "Free, independent global fitness resource. Thousands of visual workout routines requiring no equipment.", l: "Ad-free, crowd-supported", s: "Must Have" },
            { n: "Cronometer", u: "https://cronometer.com/", d: "The most accurate macro and micronutrient tracker on the market. Better data than MyFitnessPal.", l: "Free tier exists", s: "Nutrition Tracking" },
            { n: "ExRx.net", u: "https://exrx.net/", d: "Old-school but incredibly comprehensive exercise prescription and kinesiology database.", l: "None", s: "Academic standard" },
            { n: "Hevy", u: "https://www.hevyapp.com/", d: "The best modern workout tracker for weightlifting. Excellent UI to log sets, reps, and PRs.", l: "Freemium", s: "Workout Logger" },
            { n: "EatThisMuch", u: "https://www.eatthismuch.com/", d: "Generates custom meal plans globally based on your specific calorie and macro goals.", l: "Freemium", s: "Diet Planner" },
            { n: "StrengthLevel", u: "https://strengthlevel.com/", d: "Calculate your weightlifting strength standards against millions of other lifters in your weight class.", l: "None", s: "Benchmarking" },
            { n: "MacroFactor", u: "https://macrofactorapp.com/", d: "Science-backed dietary app with an algorithm that adapts to your metabolism automatically.", l: "Paid app", s: "Algorithm Diet" },
            { n: "Examine.com", u: "https://examine.com/", d: "Independent, unbiased analysis of supplements and nutrition. Finds out if that supplement actually works.", l: "Freemium", s: "Supplement Science" },
            { n: "Sleepyti.me", u: "https://sleepopolis.com/calculators/sleep/", d: "Calculates the exact time you should go to sleep or wake up to avoid waking up in the middle of a REM cycle.", l: "None", s: "Sleep Hack" },
            { n: "Yoga with Adriene", u: "https://yogawithadriene.com/", d: "The most popular, approachable, free yoga routines on the internet.", l: "None", s: "YouTube Resource" },
            { n: "Caliber", u: "https://caliberstrong.com/", d: "Genuinely free, science-based strength training app with no ads and no paywalled features for logging.", l: "None", s: "App Recommendation" },
            { n: "TDEE Calculator", u: "https://tdeecalculator.net/", d: "Find out your Total Daily Energy Expenditure (how many calories you burn everyday).", l: "None", s: "Nutrition Basics" },
            { n: "Symmetric Strength", u: "https://symmetricstrength.com/", d: "Finds your weak points in weightlifting and gives you a visual strength profile.", l: "None", s: "Lifting Analytics" },
            { n: "MyNoise", u: "https://mynoise.net/", d: "Customizable, generative soundscapes for focus, tinnitus relief, or sleep. The best white noise generator.", l: "None", s: "Audio Health" }
        ]
    },
    {
        id: "social-media", name: "🎯 Social Media Tools", icon: "📱", type: "tech",
        desc: "Planners, tag generators, and anon viewing tools.",
        sites: [
            { n: "Buffer", u: "https://buffer.com/", d: "Schedule posts across multiple social networks. The free tier is excellent for personal brands.", l: "Free tier exists", s: "Social Scheduler" },
            { n: "Linktree", u: "https://linktr.ee/", d: "Create a micro landing page for your bio linking all your projects and socials in one place.", l: "Freemium", s: "Bio Links" },
            { n: "Imgur", u: "https://imgur.com/", d: "The magic internet image host. Easiest way to drop an image to share on Reddit or forums.", l: "None", s: "Fast Hosting" },
            { n: "Giphy", u: "https://giphy.com/", d: "Find, create, and share GIFs easily.", l: "None", s: "GIF Engine" },
            { n: "Social Blade", u: "https://socialblade.com/", d: "Track YouTube, Twitch, Twitter, and Instagram statistics and estimate influencer earnings.", l: "None", s: "Analytics" },
            { n: "TweetDeck (X Pro)", u: "https://tweetdeck.twitter.com/", d: "Power-user dashboard for X (Twitter). Monitor multiple timelines and columns simultaneously.", l: "Requires X Premium", s: "Power Tool" },
            { n: "Picuki", u: "https://www.picuki.com/", d: "View and download Instagram profiles, stories, and posts completely anonymously without logging in.", l: "None", s: "Anon Viewer" },
            { n: "Display Purposes", u: "https://displaypurposes.com/", d: "Generates relevant hashtags for your Instagram post and filters out banned/spammy tags automatically.", l: "None", s: "Hashtag Tool" },
            { n: "Snaptik", u: "https://snaptik.app/", d: "Download TikTok videos without the watermark.", l: "Ads present", s: "Video Downloader" },
            { n: "TwitchTracker", u: "https://twitchtracker.com/", d: "Comprehensive statistics and tracker for Twitch streamers and viewership records.", l: "None", s: "Twitch Analytics" },
            { n: "Nitter", u: "https://nitter.net/", d: "Alternative privacy-focused, ad-free frontend for Twitter. (Note: instances change often due to API limits).", l: "FOSS", s: "Privacy Frontend" },
            { n: "Later", u: "https://later.com/", d: "Visual planner and scheduling tool primarily built around Instagram.", l: "Freemium", s: "Visual Planning" },
            { n: "Carrd", u: "https://carrd.co/", d: "Build simple, free, fully responsive one-page sites for pretty much anything.", l: "Freemium", s: "One-Page Sites" },
            { n: "Followerwonk", u: "https://followerwonk.com/", d: "Deep dive Twitter analytics. Search bios, compare users, and track behavior.", l: "Freemium", s: "Deep Analytics" },
            { n: "Hashtagify", u: "https://hashtagify.me/", d: "Find, analyze, and amplify your Twitter and Instagram hashtags.", l: "Freemium", s: "Hashtag Data" }
        ]
    },
    {
        id: "file-conversion", name: "🧰 File Conversion", icon: "📁", type: "tech",
        desc: "Format converters, PDF tools, and file compressors.",
        sites: [
            { n: "CloudConvert", u: "https://cloudconvert.com/", d: "Convert anything to anything. Supports 200+ formats (audio, video, document, ebook, image).", l: "25 conversions/day free", s: "Must Have" },
            { n: "ILovePDF", u: "https://www.ilovepdf.com/", d: "Merge, split, compress, convert, unlock, and watermark PDFs entirely in your browser.", l: "Freemium", s: "PDF Essential" },
            { n: "123Apps", u: "https://123apps.com/", d: "Huge suite of free online web apps: audio cutter, video trimmer, PDF tools, and voice recorder.", l: "None", s: "Mega Suite" },
            { n: "Convertio", u: "https://convertio.co/", d: "Fast and easy-to-use online file converter for documents, images, and videos.", l: "File size limits on free", s: "Found via research" },
            { n: "EZGIF", u: "https://ezgif.com/", d: "Simple online GIF maker and toolset for basic animated GIF editing, cropping, and optimizing.", l: "None", s: "GIF Essential" },
            { n: "PDF24", u: "https://tools.pdf24.org/", d: "100% free PDF tools with zero limitations. Extract pages, protect, unprotect, and convert.", l: "None", s: "Ad-Free Alternative" },
            { n: "Zamzar", u: "https://www.zamzar.com/", d: "One of the oldest and most reliable online file converters.", l: "File limits", s: "Classic Tool" },
            { n: "Online-Convert", u: "https://www.online-convert.com/", d: "Convert media files from one format to another online.", l: "Freemium", s: "Found via research" },
            { n: "PDF Candy", u: "https://pdfcandy.com/", d: "44 online PDF tools including OCR, cropping, and extensive conversions.", l: "Freemium", s: "PDF Toolkit" },
            { n: "Kapwing", u: "https://www.kapwing.com/", d: "Collaborative online video editor. Good for resizing, converting, and formatting videos for social media.", l: "Watermark on free", s: "Social Video" },
            { n: "VideoToMe", u: "https://video2me.net/", d: "Convert YouTube links to MP3/MP4, trim video, and remove audio.", l: "Ads present", s: "Media Tool" },
            { n: "Notta", u: "https://www.notta.ai/", d: "Audio and video to text transcription. Convert voice memos to accurate text.", l: "Freemium", s: "Transcription" },
            { n: "FreeConvert", u: "https://www.freeconvert.com/", d: "Upload massive files (up to 1GB free) for various format conversions.", l: "Free tier exists", s: "Large Files" },
            { n: "Photopea", u: "https://www.photopea.com/", d: "Open PSD files in your browser and export them as standard JPG/PNGs.", l: "None", s: "Browser Editor" },
            { n: "Vectorizer", u: "https://www.vectorizer.io/", d: "Convert raster images like PNGs, BMPs and JPEGs to scalable vector graphics (SVG, EPS, DXF).", l: "Freemium", s: "Vectorization" }
        ]
    },
    {
        id: "books-reading", name: "📖 Books & Reading", icon: "📚", type: "edu",
        desc: "Free ebooks, public domain literature, speed reading, and book trackers.",
        sites: [
            { n: "Project Gutenberg", u: "https://www.gutenberg.org/", d: "Library of over 70,000 free eBooks. Focuses on older works where US copyright has expired.", l: "None", s: "Public Domain" },
            { n: "Goodreads", u: "https://www.goodreads.com/", d: "The world's largest site for readers and book recommendations.", l: "None", s: "Massive Community" },
            { n: "Standard Ebooks", u: "https://standardebooks.org/", d: "Beautifully formatted, carefully curated, public domain ebooks without the weird formatting commonly found on Gutenberg.", l: "None", s: "High Quality" },
            { n: "Library Genesis (LibGen)", u: "https://libgen.is/", d: "Shadow library for millions of academic papers, textbooks, and epub fiction.", l: "Piracy", s: "Shadow Library" },
            { n: "Z-Library", u: "https://singlelogin.re/", d: "One of the largest shadow libraries for books and scholarly articles. (Domains change frequently).", l: "Piracy", s: "Shadow Library" },
            { n: "Internet Archive: Text", u: "https://archive.org/details/texts", d: "Millions of digitized books. Many can be physically 'borrowed' digitally using OCR tech.", l: "Free", s: "Digital Borrowing" },
            { n: "StoryGraph", u: "https://app.thestorygraph.com/", d: "The best alternative to Goodreads. Includes amazing charts, half-star ratings, and mood-based discovery.", l: "Freemium", s: "Reader Analytics" },
            { n: "Anna's Archive", u: "https://annas-archive.org/", d: "Meta-search engine unifying Z-Library, LibGen, and Sci-Hub to backup human knowledge.", l: "Shadow Library", s: "Backup Project" },
            { n: "Open Library", u: "https://openlibrary.org/", d: "An open, editable library catalog aiming to have one web page for every book ever published.", l: "None", s: "Cataloging" },
            { n: "ThriftBooks", u: "https://www.thriftbooks.com/", d: "Buy physical used books incredibly cheap. Better support the industry than buying from Amazon.", l: "Store", s: "Cheap Books" },
            { n: "Bionic Reading", u: "https://bionic-reading.com/", d: "Tool that systematically bolds parts of words to guide the eyes over text, facilitating speed reading.", l: "Freemium", s: "Speed Reading" },
            { n: "LibriVox", u: "https://librivox.org/", d: "Free public domain audiobooks read by volunteers.", l: "None", s: "Free Audiobooks" },
            { n: "Squibler", u: "https://www.squibler.io/dangerous-writing-prompt-app", d: "The most dangerous writing app: if you stop typing for more than 5 seconds, all your progress is deleted.", l: "None", s: "Writer Tool" },
            { n: "ManyBooks", u: "https://manybooks.net/", d: "More than 50,000 free ebooks waiting to be discovered.", l: "None", s: "Free Discovery" },
            { n: "Blinkist", u: "https://www.blinkist.com/", d: "Read or listen to the key takeaways from nonfiction books in 15 minutes.", l: "Paid", s: "Book Summaries" }
        ]
    }
);
